version: 2
jobs:
  test-node-9:
    working_directory: ~/mobile-wallet
    docker:
      - image: circleci/node:8-browsers
    steps: &teststeps
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name : Install pre dependencies
          command : sudo npm i -g ionic@4.x cordova@8.x
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run:
          name: Lint
          command: npm run lint --bailOnLintError true
      - run:
          name: Unit tests
          command: npm run test:coverage
      - run:
          name: e2e tests
          command: npm run test:e2e
      - run:
          name: Build
          command: npm run build -- --prod

  test-node-stable:
      working_directory: ~/mobile-wallet
      docker:
        - image: circleci/node:latest-browsers
      steps: *teststeps

workflows:
  version: 2
  test:
    jobs:
      - test-node-9
      - test-node-stable
